### ISSUE TITLE
libxml2-dev , libxslt-dev needed ?

### ISSUE THREAD

**Issue by eprschmidt** [thokari/docker-ansible#2]
hi @thokari ,

can you answer me
why is libxml2-dev , libxslt-dev needed ?
see https://github.com/thokari/docker-ansible/blob/master/Dockerfile#L10 ?  

Regards
Regine

**Comment by thokari** [comment]
Sorry for the late reply @eprschmidt .

The libraries are needed, because they are a dependency of the `lxml` Python module, which is used by the `xml` module of Ansible.
See https://docs.ansible.com/ansible/latest/collections/community/general/xml_module.html
and https://lxml.de/installation.html
I would have forgotten as well, had I not put the comment there.

**Comment by eprschmidt** [comment]
hi @thokari,
thank you for your answer
:-D
